In [3]:
import torch 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

device = "cuda" if torch.cuda.is_available() else "cpu"
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensor 
Creating tensor 

In [5]:
#scalar 
scalar = torch.tensor(8)
scalar 

tensor(8)

In [6]:
scalar.ndim 

0

In [12]:
#Get tensor back as python int 
scalar.item()
MATRIX = torch.tensor([[9,9],
                       [9,3]])

print(MATRIX)
print(MATRIX.ndim)
print(MATRIX[1])
print(MATRIX.shape)

tensor([[9, 9],
        [9, 3]])
2
tensor([9, 3])
torch.Size([2, 2])


In [20]:
# Tensor 
TENSOR = torch.tensor([[[9,9,4],
                       [3,3,4],
                       [5,6,7]]])

print(TENSOR)
print(TENSOR.ndim)


tensor([[[9, 9, 4],
         [3, 3, 4],
         [5, 6, 7]]])
3


In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

### RANDOM TENSOR 

### Random Tensors 

Why Random Tensors 

Random tensors are important because the way many neural networks learn is thath they start with tensors full of random numbers and the adjust those random numbers to better represent the data 

"start with random numbers -> look at data -> update random numbers -> look at data -> update"

In [31]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.1751, 0.8122, 0.9455, 0.0991],
        [0.1987, 0.3586, 0.6596, 0.7811],
        [0.4290, 0.7464, 0.8066, 0.6304]])

In [5]:
#creater a random tensor with similar shape to image tensor 

random_img_tensor_size = torch.rand(size=(3,224,224))
random_img_tensor_size.shape, random_img_tensor_size.ndim 

(torch.Size([3, 224, 224]), 3)

### Creating a range of tensors and tensors_like

In [12]:
one_to_ten = torch.arange(start = 1, end = 11, step = 1) # Use torch.range()
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
# Creating tensors like 

ten_zero = torch.zeros_like(one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Dealing Tensor With Data Type 

**Note** Tensor datatype is one of the 3 big issues (error) with PyTorch & deep Learning: 
1. Tensors not right datatype 
2. Tensors nor right device 
3. tensors not on the right device 

In [35]:
# Float 32 tensor 

float_32_tensor = torch.tensor([3.0, 4.0, 5.0], 
                               dtype=torch.float32, # mengatur data type apa yang di gunakan 
                               device=device, # device apa yang di gunakan
                               requires_grad=True) # wheter or not to track gradients with this tensors operation 

float_32_tensor

tensor([3., 4., 5.], device='cuda:0', requires_grad=True)

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], device='cuda:0', dtype=torch.float16,
       grad_fn=<ToCopyBackward0>)

In [33]:
float_16_tensor * float_32_tensor 

tensor([ 9., 16., 25.], device='cuda:0', grad_fn=<MulBackward0>)

In [38]:
int_32_tensor = torch.tensor([3, 4, 5],
                             dtype =torch.int32,device=device) 
int_32_tensor

tensor([3, 4, 5], device='cuda:0', dtype=torch.int32)

### *Getting Information* (tensor Attributes)
1. Tensors not right datatype - to do get dataype from a tensor, can use **'tensor.dtype'*** 
2. Tensors nor right device  - to get shape from a tensor, can use **'tensor.shape'**
3. tensors not on the right device - to get device from a tensor, can use **'tensor.device'** 

In [52]:
some_tensor = torch.rand([3,24,16]).to(device)
some_tensor

tensor([[[0.5361, 0.0464, 0.9470,  ..., 0.1231, 0.8638, 0.5782],
         [0.3793, 0.2940, 0.3980,  ..., 0.5652, 0.0720, 0.2427],
         [0.8654, 0.4176, 0.1876,  ..., 0.5474, 0.0480, 0.7785],
         ...,
         [0.2475, 0.4016, 0.1856,  ..., 0.8480, 0.1209, 0.3766],
         [0.7865, 0.3382, 0.5211,  ..., 0.3692, 0.4393, 0.8419],
         [0.3878, 0.6613, 0.6602,  ..., 0.0698, 0.5550, 0.6383]],

        [[0.8348, 0.1303, 0.9969,  ..., 0.1451, 0.6468, 0.8021],
         [0.5347, 0.3743, 0.2893,  ..., 0.4912, 0.2547, 0.0291],
         [0.5604, 0.6179, 0.1155,  ..., 0.4981, 0.9779, 0.9034],
         ...,
         [0.8212, 0.5600, 0.6503,  ..., 0.5275, 0.5009, 0.7228],
         [0.4104, 0.6877, 0.5213,  ..., 0.0666, 0.4127, 0.9472],
         [0.5620, 0.8380, 0.1972,  ..., 0.3045, 0.8264, 0.4344]],

        [[0.7890, 0.8154, 0.8668,  ..., 0.4380, 0.3910, 0.2235],
         [0.3206, 0.3504, 0.5642,  ..., 0.3416, 0.1518, 0.1214],
         [0.4006, 0.6502, 0.5406,  ..., 0.4596, 0.8178, 0.

In [53]:
print(some_tensor)
print(f"Tipe data dari tensor : {some_tensor.dtype}")
print(f"Shape dari tensor : {some_tensor.shape}")
print(f"device dari tensor : {some_tensor.device}")

tensor([[[0.5361, 0.0464, 0.9470,  ..., 0.1231, 0.8638, 0.5782],
         [0.3793, 0.2940, 0.3980,  ..., 0.5652, 0.0720, 0.2427],
         [0.8654, 0.4176, 0.1876,  ..., 0.5474, 0.0480, 0.7785],
         ...,
         [0.2475, 0.4016, 0.1856,  ..., 0.8480, 0.1209, 0.3766],
         [0.7865, 0.3382, 0.5211,  ..., 0.3692, 0.4393, 0.8419],
         [0.3878, 0.6613, 0.6602,  ..., 0.0698, 0.5550, 0.6383]],

        [[0.8348, 0.1303, 0.9969,  ..., 0.1451, 0.6468, 0.8021],
         [0.5347, 0.3743, 0.2893,  ..., 0.4912, 0.2547, 0.0291],
         [0.5604, 0.6179, 0.1155,  ..., 0.4981, 0.9779, 0.9034],
         ...,
         [0.8212, 0.5600, 0.6503,  ..., 0.5275, 0.5009, 0.7228],
         [0.4104, 0.6877, 0.5213,  ..., 0.0666, 0.4127, 0.9472],
         [0.5620, 0.8380, 0.1972,  ..., 0.3045, 0.8264, 0.4344]],

        [[0.7890, 0.8154, 0.8668,  ..., 0.4380, 0.3910, 0.2235],
         [0.3206, 0.3504, 0.5642,  ..., 0.3416, 0.1518, 0.1214],
         [0.4006, 0.6502, 0.5406,  ..., 0.4596, 0.8178, 0.

### Manipulating Tensors (tensor Operations) 

tensor operations incule : 
* addition 
* substraction 
* multiplication (element-wise)
* division 
* matrix multiplication 


In [82]:
tensor = torch.tensor([1,2,3]) # addition 
tensor + 10 

tensor([11, 12, 13])

In [74]:
tensor = tensor / 10 # multiplication
tensor

tensor([0.1000, 0.2000, 0.3000])

In [80]:
# Try out Pytoch built-in functions 

torch.add(tensor, torch.rand(3))

tensor([0.4433, 0.4522, 0.5942])

### Matrix multipication 
Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix mutliplication (dot product)

There are two main rules that performing matrix mutliplication needs to satisfy:
1. The **inner dimentions** must match:
* '(3,2) @ (3,2)' won't work 
* '(2,3) @ (3,2)' will work 
* '(3,2) @ (2,3)' will work 
2. the resulting matrix has the sape of the **outer dimensions** 
* '(2,3) @ (3,2)' -> '(2,2)' 
* '(3,2) @ (2,3)' -> '(3,3)'

In [103]:
torch.matmul(torch.rand(10,10),torch.rand(10,10)).shape

torch.Size([10, 10])

In [89]:
# Element wise multiplication 
print(tensor, "*" , tensor ) 
print(f"Equals : {tensor.mul(tensor)}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [92]:
torch.matmul(tensor,tensor) # -> 1*1 + 2*2 + 3*3 = 14

tensor(14)

In [93]:
%%time 

value = 0 
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 6.56 ms


In [95]:
%%time 
torch.matmul(tensor, tensor) 

CPU times: total: 0 ns
Wall time: 544 μs


tensor(14)

One of the most common errors in deep learning: shape errors

In [ ]:
# shape for matrix multipication 
tensor_a = torch.rand(3,4)
tensor_b = torch.rand(3,4) 

torch.mm(tensor_a,tensor_b) 

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.
A **transpose** switches the axes or dimensions of a given tensor.

In [108]:
tensor_a , tensor_a.T.shape

(tensor([[0.5211, 0.0313, 0.5105, 0.3025],
         [0.0271, 0.4713, 0.5969, 0.0111],
         [0.2232, 0.1496, 0.5006, 0.3369]]),
 torch.Size([4, 3]))

In [ ]:
print(f" Original shapes: tensor _ A {tensor_a.shape}, tensor B {tensor_b.shape}")  
print(f"New shape :tensor_a ={tensor_a.T.shape} (same shape as above), tensor_b.T = {tensor_b.shape}")
print(f"Multiplying: {tensor_a.T.shape} @ {tensor_b.shape} inner dimensions must match")
print ("Output: \n" )
output = torch.matmul(tensor_a.T,tensor_b)
print (output)
print(f"Output shape: {output.shape}")

 Original shapes: tensor _ A torch.Size([3, 4]), tensor B torch.Size([3, 4])
New shape :tensor_a =torch.Size([4, 3]) (same shape as above), tensor_b.T = torch.Size([3, 4])
Multiplying: torch.Size([4, 3]) @ torch.Size([3, 4]) inner dimensions must match
Output: 

tensor([[0.4146, 0.1198, 0.1373, 0.2871],
        [0.5800, 0.4326, 0.2010, 0.4738],
        [1.1664, 0.6676, 0.4254, 0.9275],
        [0.3894, 0.1256, 0.1796, 0.3264]])
Output shape: torch.Size([4, 4])


### Finding the min, max, mean, sum, etc (tensor aggregation )

In [ ]:
# create a tensor 
x = torch.arange(0,100,10)
x.dtype 

torch.int64

In [131]:
# find the min 
x.min(), x.max()

(tensor(0), tensor(90))

In [ ]:
# Find the mean-note: the torch.mean() function requires a tensor of float 32 datatype to work
torch.mean(x.type(torch.float32)) , torch.std(x.type(torch.float32))

(tensor(45.), tensor(30.2765))

In [129]:
# find the sum 
x.sum() , torch.sum(x)

(tensor(450), tensor(450))