In [1]:
import torch 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

device = "cuda" if torch.cuda.is_available() else "cpu"
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensor 
Creating tensor 

In [2]:
#scalar 
scalar = torch.tensor(8)
scalar 

tensor(8)

In [3]:
scalar.ndim 

0

In [4]:
#Get tensor back as python int 
scalar.item()
MATRIX = torch.tensor([[9,9],
                       [9,3]])

print(MATRIX)
print(MATRIX.ndim)
print(MATRIX[1])
print(MATRIX.shape)

tensor([[9, 9],
        [9, 3]])
2
tensor([9, 3])
torch.Size([2, 2])


In [5]:
# Tensor 
TENSOR = torch.tensor([[[9,9,4],
                       [3,3,4],
                       [5,6,7]]])

print(TENSOR)
print(TENSOR.ndim)


tensor([[[9, 9, 4],
         [3, 3, 4],
         [5, 6, 7]]])
3


In [6]:
TENSOR.shape

torch.Size([1, 3, 3])

### RANDOM TENSOR 

### Random Tensors 

Why Random Tensors 

Random tensors are important because the way many neural networks learn is thath they start with tensors full of random numbers and the adjust those random numbers to better represent the data 

"start with random numbers -> look at data -> update random numbers -> look at data -> update"

In [7]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.0096, 0.9565, 0.3148, 0.5884],
        [0.7853, 0.3816, 0.1132, 0.5854],
        [0.4365, 0.9452, 0.2532, 0.6910]])

In [8]:
#creater a random tensor with similar shape to image tensor 

random_img_tensor_size = torch.rand(size=(3,224,224))
random_img_tensor_size.shape, random_img_tensor_size.ndim 

(torch.Size([3, 224, 224]), 3)

### Creating a range of tensors and tensors_like

In [9]:
one_to_ten = torch.arange(start = 1, end = 11, step = 1) # Use torch.range()
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# Creating tensors like 

ten_zero = torch.zeros_like(one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Dealing Tensor With Data Type 

**Note** Tensor datatype is one of the 3 big issues (error) with PyTorch & deep Learning: 
1. Tensors not right datatype 
2. Tensors nor right device 
3. tensors not on the right device 

In [11]:
# Float 32 tensor 

float_32_tensor = torch.tensor([3.0, 4.0, 5.0], 
                               dtype=torch.float32, # mengatur data type apa yang di gunakan 
                               device=device, # device apa yang di gunakan
                               requires_grad=True) # wheter or not to track gradients with this tensors operation 

float_32_tensor

tensor([3., 4., 5.], device='cuda:0', requires_grad=True)

In [12]:
float_32_tensor.dtype

torch.float32

In [13]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], device='cuda:0', dtype=torch.float16,
       grad_fn=<ToCopyBackward0>)

In [14]:
float_16_tensor * float_32_tensor 

tensor([ 9., 16., 25.], device='cuda:0', grad_fn=<MulBackward0>)

In [15]:
int_32_tensor = torch.tensor([3, 4, 5],
                             dtype =torch.int32,device=device) 
int_32_tensor

tensor([3, 4, 5], device='cuda:0', dtype=torch.int32)

### *Getting Information* (tensor Attributes)
1. Tensors not right datatype - to do get dataype from a tensor, can use **'tensor.dtype'*** 
2. Tensors nor right device  - to get shape from a tensor, can use **'tensor.shape'**
3. tensors not on the right device - to get device from a tensor, can use **'tensor.device'** 

In [16]:
some_tensor = torch.rand([3,24,16]).to(device)
some_tensor

tensor([[[0.5842, 0.2355, 0.5840,  ..., 0.4394, 0.2238, 0.8040],
         [0.6253, 0.2123, 0.1982,  ..., 0.6038, 0.1170, 0.8149],
         [0.6273, 0.7306, 0.1288,  ..., 0.3458, 0.7228, 0.1424],
         ...,
         [0.5409, 0.0653, 0.2365,  ..., 0.6256, 0.3178, 0.5142],
         [0.4649, 0.8726, 0.2242,  ..., 0.8241, 0.4701, 0.4163],
         [0.4556, 0.4455, 0.2435,  ..., 0.3167, 0.7744, 0.8555]],

        [[0.2004, 0.5241, 0.9759,  ..., 0.8785, 0.2864, 0.1746],
         [0.6854, 0.4033, 0.4740,  ..., 0.8136, 0.5177, 0.9372],
         [0.6565, 0.9598, 0.8090,  ..., 0.1049, 0.0391, 0.0755],
         ...,
         [0.6586, 0.4166, 0.3230,  ..., 0.2743, 0.8770, 0.6889],
         [0.1053, 0.0372, 0.1134,  ..., 0.3379, 0.3193, 0.0288],
         [0.3094, 0.1938, 0.3151,  ..., 0.5321, 0.5719, 0.9626]],

        [[0.2414, 0.3346, 0.5878,  ..., 0.5424, 0.6406, 0.6494],
         [0.2318, 0.6011, 0.5836,  ..., 0.5923, 0.1553, 0.9961],
         [0.0493, 0.3652, 0.3020,  ..., 0.0687, 0.9981, 0.

In [17]:
print(some_tensor)
print(f"Tipe data dari tensor : {some_tensor.dtype}")
print(f"Shape dari tensor : {some_tensor.shape}")
print(f"device dari tensor : {some_tensor.device}")

tensor([[[0.5842, 0.2355, 0.5840,  ..., 0.4394, 0.2238, 0.8040],
         [0.6253, 0.2123, 0.1982,  ..., 0.6038, 0.1170, 0.8149],
         [0.6273, 0.7306, 0.1288,  ..., 0.3458, 0.7228, 0.1424],
         ...,
         [0.5409, 0.0653, 0.2365,  ..., 0.6256, 0.3178, 0.5142],
         [0.4649, 0.8726, 0.2242,  ..., 0.8241, 0.4701, 0.4163],
         [0.4556, 0.4455, 0.2435,  ..., 0.3167, 0.7744, 0.8555]],

        [[0.2004, 0.5241, 0.9759,  ..., 0.8785, 0.2864, 0.1746],
         [0.6854, 0.4033, 0.4740,  ..., 0.8136, 0.5177, 0.9372],
         [0.6565, 0.9598, 0.8090,  ..., 0.1049, 0.0391, 0.0755],
         ...,
         [0.6586, 0.4166, 0.3230,  ..., 0.2743, 0.8770, 0.6889],
         [0.1053, 0.0372, 0.1134,  ..., 0.3379, 0.3193, 0.0288],
         [0.3094, 0.1938, 0.3151,  ..., 0.5321, 0.5719, 0.9626]],

        [[0.2414, 0.3346, 0.5878,  ..., 0.5424, 0.6406, 0.6494],
         [0.2318, 0.6011, 0.5836,  ..., 0.5923, 0.1553, 0.9961],
         [0.0493, 0.3652, 0.3020,  ..., 0.0687, 0.9981, 0.

### Manipulating Tensors (tensor Operations) 

tensor operations incule : 
* addition 
* substraction 
* multiplication (element-wise)
* division 
* matrix multiplication 


In [18]:
tensor = torch.tensor([1,2,3]) # addition 
tensor + 10 

tensor([11, 12, 13])

In [19]:
tensor = tensor / 10 # multiplication
tensor

tensor([0.1000, 0.2000, 0.3000])

In [20]:
# Try out Pytoch built-in functions 

torch.add(tensor, torch.rand(3))

tensor([0.7650, 0.5885, 0.9052])

### Matrix multipication 
Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix mutliplication (dot product)

There are two main rules that performing matrix mutliplication needs to satisfy:
1. The **inner dimentions** must match:
* '(3,2) @ (3,2)' won't work 
* '(2,3) @ (3,2)' will work 
* '(3,2) @ (2,3)' will work 
2. the resulting matrix has the sape of the **outer dimensions** 
* '(2,3) @ (3,2)' -> '(2,2)' 
* '(3,2) @ (2,3)' -> '(3,3)'

In [21]:
torch.matmul(torch.rand(10,10),torch.rand(10,10)).shape

torch.Size([10, 10])

In [22]:
# Element wise multiplication 
print(tensor, "*" , tensor ) 
print(f"Equals : {tensor.mul(tensor)}")

tensor([0.1000, 0.2000, 0.3000]) * tensor([0.1000, 0.2000, 0.3000])
Equals : tensor([0.0100, 0.0400, 0.0900])


In [23]:
torch.matmul(tensor,tensor) # -> 1*1 + 2*2 + 3*3 = 14

tensor(0.1400)

In [24]:
%%time 

value = 0 
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(0.1400)
CPU times: total: 0 ns
Wall time: 4.51 ms


In [25]:
%%time 
torch.matmul(tensor, tensor) 

CPU times: total: 0 ns
Wall time: 818 μs


tensor(0.1400)

One of the most common errors in deep learning: shape errors

In [26]:
# shape for matrix multipication 
tensor_a = torch.rand(3,4)
tensor_b = torch.rand(3,4) 

torch.mm(tensor_a,tensor_b) 

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.
A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_a , tensor_a.T.shape

In [27]:
print(f"Original shapes: tensor_a {tensor_a.shape}, tensor B {tensor_b.shape}")  
print(f"New shape :tensor_a ={tensor_a.T.shape} (same shape as above), tensor_b.T = {tensor_b.shape}")
print(f"Multiplying: {tensor_a.T.shape} @ {tensor_b.shape} inner dimensions must match")
print ("Output: \n" )

output = torch.matmul(tensor_a.T,tensor_b)

print (output)
print("\n")
print(f"Output shape: {output.shape}")

Original shapes: tensor_a torch.Size([3, 4]), tensor B torch.Size([3, 4])
New shape :tensor_a =torch.Size([4, 3]) (same shape as above), tensor_b.T = torch.Size([3, 4])
Multiplying: torch.Size([4, 3]) @ torch.Size([3, 4]) inner dimensions must match
Output: 

tensor([[0.7679, 0.1962, 0.1245, 0.4062],
        [0.5379, 0.2817, 0.1229, 0.7300],
        [0.6332, 0.2454, 0.0662, 0.5932],
        [0.8586, 0.3474, 0.1686, 0.8496]])


Output shape: torch.Size([4, 4])


### Finding the min, max, mean, sum, etc (tensor aggregation )

In [28]:
# create a tensor 
x = torch.arange(0,100,10)
x.dtype 

torch.int64

In [29]:
# find the min 
x.min(), x.max()

(tensor(0), tensor(90))

In [30]:
# Find the mean-note: the torch.mean() function requires a tensor of float 32 datatype to work
torch.mean(x.type(torch.float32)) , torch.std(x.type(torch.float32)) 

(tensor(45.), tensor(30.2765))

In [31]:
# find the sum 
x.sum() , torch.sum(x) 

(tensor(450), tensor(450))

## Finding the position min and max 

In [32]:
# Find the the position of min and max value using "arg" with min and max value accure 
x.argmin(), x.argmax() 

(tensor(0), tensor(9))

In [33]:
y = torch.rand(3,3)
y

tensor([[0.4367, 0.3260, 0.3334],
        [0.8506, 0.5995, 0.3290],
        [0.6621, 0.2611, 0.8333]])

In [34]:
y.argmax(), y.argmin()

(tensor(3), tensor(7))

### Reshaping,stacking,squeezing, and unsqueezing tensors 
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - adda 1 dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [35]:
# Let's create a tensor 
p = torch.arange(1., 10.)
p , p.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [47]:
# add an extra dimension 
p_reshaped = p.reshape(1,9)
p_reshaped , p_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [44]:
p 

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
# Change the view 
z = p.view(1, 9)
z, z.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [40]:
#change z changes p (because a view of a tensor shares the same memory as the original one 
z[:,0] = 5 
z, p

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [53]:
# Stack the tensor each other 
p_stack = torch.stack([p,p,p,p], dim = 1) 
p_stack 


tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [56]:
# toch.squeeze() - remove all single dimensions from a target tensor 
print(f"Tensor sebelumnya : {p_reshaped}") 
print(f"Shape tensor sebelumnya : {p_reshaped.shape}") 

# remove extra dimensions from p_reshaped 
p_squeezed = p_reshaped.squeeze() 
print(f"\nnew tensor : {p_squeezed}") 
print(f"shape new tensor : {p_squeezed.shape}") 

Tensor sebelumnya : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Shape tensor sebelumnya : torch.Size([1, 9])

new tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
shape new tensor : torch.Size([9])


In [66]:
# torch.unsqueeze () - add a single dimensions to a target tensor ata specific dim (dimensions) 

print(f"Previouse Target : {p_squeezed}") 
print(f"Previouse Target shape : {p_squeezed.shape}") 

#add an extra dimension with unsqueeze 
p_unsqueeze = p_squeezed.unsqueeze(dim = 0) 
print(f"\nnew tensor : {p_unsqueeze}") 
print(f"shape new tensor : {p_unsqueeze.shape}") 

Previouse Target : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previouse Target shape : torch.Size([9])

new tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
shape new tensor : torch.Size([1, 9])


In [50]:
p_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [52]:
p_reshaped.squeeze().shape

torch.Size([9])

In [70]:
# torch permute - rearrange the dimensions of a target tensor in a specified order 
x_original = torch.rand(size  = (224,224,3)) # (height,width, colour_channels) 

# permute the original tensor to rearrange the axis (or dim) order 
x_permuted = x_original.permute(2,0,1) # shift axis 0-> 1 , 1 -> 2 , 2 -> 0 

print(f"Previouse shape : {x_original.shape}") 
print(f"new shape : {x_permuted.shape}") # [colour_channels, height, width 

Previouse shape : torch.Size([224, 224, 3])
new shape : torch.Size([3, 224, 224])


In [74]:
x_original[0,0,0] = 0.8  

In [76]:
x_permuted[0,0,0] , x_original[0,0,0] 

(tensor(0.8000), tensor(0.8000))

### Indexing (selecting data from tensors) 
indexing with pytorch is similar to indexing with numpy 

In [82]:
# Create a tensor 
x = torch.arange(1,10).reshape(1,3,3) 
x, x.shape 

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [100]:
# let's index the new tensor 
x[0] 

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [87]:
# Indexing on middle bracket 
x[0][0] 

tensor([1, 2, 3])

In [94]:
# Let's index on the most inner bracket (last dimension) 
x[0][2][2] 

tensor(9)

In [98]:
#can also use ":" to select "all" of a target dimension 
x[:,1] 

tensor([[4, 5, 6]])

In [107]:
# get all values of 0th and 1st dimension but only index 2of 2nd dimension 
x[:,:,2] 

tensor([[3, 6, 9]])

In [109]:
x[:,1,1] # Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension 

tensor([5])

In [110]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0,0,:]

tensor([1, 2, 3])

## PyTorch tensors & numpy 

Numpy is a popular scientific python numerical computing library. and because of this, PyTorch has fucntionally to interect with it. 
* Data in NumPy, want in PyTorch tensor -> 'torch.from_numpy(ndarray)'
* Pytorch tensor -> NumPy -> 'torch.Tensor.numpy()'

In [115]:
# Numpy array to tensor 

array = np.arange(1.0, 8.0) 
tensor = torch.from_numpy(array) # dtype data array numpy akan mengikut ke tensor 
array,tensor 

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [113]:
array.dtype # default numpy dtype

dtype('float64')

In [117]:
array = array + 1 # Penggantian pada original array (numpy) tidak berpengaruh ke tensor 
array , tensor 

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [120]:
#Tensor to numpy 
tensor = torch.rand(7) 
numpy_tensor = tensor.numpy() 
tensor,numpy_tensor 

(tensor([0.5254, 0.8711, 0.6061, 0.1587, 0.2317, 0.9228, 0.9406]),
 array([0.5253649 , 0.8710727 , 0.60606724, 0.15874553, 0.23173422,
        0.92284536, 0.94058114], dtype=float32))

In [121]:
tensor = tensor + 1 # Penggantian pada  tensor original  tidak berpengaruh ke array (numpy)
numpy_tensor, tensor 

(array([0.5253649 , 0.8710727 , 0.60606724, 0.15874553, 0.23173422,
        0.92284536, 0.94058114], dtype=float32),
 tensor([1.5254, 1.8711, 1.6061, 1.1587, 1.2317, 1.9228, 1.9406]))

### Reproducbility (Trying to take random out of random) 

in short how a nural network learns : 

'Start with random numbers -> tensor operations -> update random numbers to try and make them better of the data -> again -> again -> again ...' 

to reduce a randomness in Neural networks and PyTorch comes the concept of a **random seed**
essentially what the random seed dose is "flavour" the randomness 

In [122]:
# Crate two Random Tensor 
random_tensor_A = torch.rand(3,4) 
random_tensor_B = torch.rand(3,4) 

print(random_tensor_A)
print(random_tensor_B) 
print(random_tensor_A == random_tensor_B) 

tensor([[0.0330, 0.0142, 0.5117, 0.0884],
        [0.4532, 0.1579, 0.1224, 0.2373],
        [0.9192, 0.8339, 0.8619, 0.5706]])
tensor([[0.9736, 0.7819, 0.7224, 0.2185],
        [0.5290, 0.5891, 0.4357, 0.1796],
        [0.2670, 0.1805, 0.5404, 0.2218]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [125]:
# Let's make some random but reproducible tensor 

# set_random seed --> gunanya ini itu supaya tidak terlalu random tensornya 
RANDOM_SEED = 42 

torch.manual_seed(RANDOM_SEED) # hanya bisa di lakukan per 1 baris 
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4) 

print(random_tensor_C)
print(random_tensor_D) 
print(random_tensor_C == random_tensor_D) 

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running Tensors and Pytorch on GPU for running it faster 

GPUs == faster computaion on numbers **CUDA** 

### 1. Getting A GPU 
* using google colab
* Your own GPU
* USe cloud computing - GCP,AWS,Azure 